### ISSUE TITLE
Missing Header/hpp file?

### ISSUE THREAD

**Issue by Leprechaun817** [neobrain/blobify#2]
Your example that's included on the readme and the bmp example that you provide use a hpp file called "stream_storage.hpp". I was trying to recreate your example for myself but I can't find this file anywhere. Is memory_storage.hpp a replacement for it, or do we need stream_storage.hpp for these examples to work properly?

**Comment by neobrain** [comment]
Fixed in 5c4351cf9caa99cbdbcfb4ef4639cd1689cdf3d4. Thanks for the report!

I'm sure you already guessed, but for reference memory_storage and stream_storage are both implementations of the same concept (providing an interface to read/write serialized data), where the former refers to data in RAM and the latter refers to data accessed using an `std::stream`.
